apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    alertmanagerMain:
      nodeSelector: 
        node-role.kubernetes.io/monitoring: ""
      tolerations:
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoSchedule
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoExecute
    prometheusK8s:
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      tolerations:
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoSchedule
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoExecute
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      tolerations:
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoSchedule
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoExecute
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      tolerations:
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoSchedule
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoExecute
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      tolerations:
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoSchedule
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoExecute
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      tolerations:
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoSchedule
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoExecute
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      tolerations:
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoSchedule
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoExecute
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      tolerations:
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoSchedule
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoExecute
    monitoringPlugin:
      nodeSelector:
        node-role.kubernetes.io/monitoring: ""
      tolerations:
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoSchedule
      - key: node-role.kubernetes.io/monitoring
        value: reserved
        effect: NoExecute