apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec:
  disableAllDefaultSources: false
  sources:
    - disabled: false
      name: community-operators
    - disabled: false
      name: redhat-operators
    - disabled: false
      name: certified-operators
    - disabled: false
      name: redhat-marketplace