- name: Install packages
  ansible.builtin.yum:
    name: haproxy
    state: latest

- name: Generate haproxy conf
  ansible.builtin.template:
    src: conf/loadbalancer/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    mode: '0660'
    validate: /sbin/haproxy -f %s -c
    backup: yes

#Maybe necessary setsebool -P haproxy_connect_any=1
- name: Allow haproxy to listen on ports
  community.general.seport:
    ports: 
      - 80
      - 443
      - 6443
      - 8000
      - 8404
      - 22623
    proto: tcp
    setype: http_port_t
    state: present

- name: Allow ports through firewall
  ansible.posix.firewalld:
    port: '{{ item }}/tcp'
    zone: public
    immediate: true
    permanent: true
    state: enabled
  loop: 
    - 80
    - 443
    - 6443
    - 8000
    - 8404
    - 22623

- name: Restart service haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Enable service haproxy
  ansible.builtin.service:
    name: haproxy
    enabled: true