- name: Install packages
  ansible.builtin.yum:
    name: haproxy
    state: latest

- name: Generate haproxy conf
  ansible.builtin.template:
    src: conf/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    mode: '0660'
    validate: /sbin/haproxy -f %s -c
    backup: yes

- name: Allow haproxy to listen on ports
  community.general.seport:
    ports: 
      - 80
      - 443
      - 6443
      - 8000
      - 22623
      - 8404
    proto: tcp
    setype: http_port_t
    state: present

- name: Allow ports through firewall
  ansible.posix.firewalld:
    port: '{{ item }}/tcp'
    zone: public
    immediate: true
    permanent: true
    state: enabled
  loop: 
    - 80
    - 443
    - 6443
    - 8000
    - 22623
    - 8404

- name: Restart service haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Enable service haproxy
  ansible.builtin.service:
    name: haproxy
    enabled: yes

- name: Copy ignition-http.service
  ansible.builtin.copy:
    src: conf/http-ignition.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'
    
- name: Start http-ignition.service
  ansible.builtin.systemd_service:
    state: started
    name: http-ignition
    daemon_reload: true