- name: Disable cloud-init service
  ansible.builtin.service:
    name: cloud-init
    state: stopped
    enabled: false

- name: Create installation directory
  ansible.builtin.file:
    path: /root/installation
    state: directory

- name: Check if openshift-install is installed
  ansible.builtin.shell: |
    if [[ -f /root/openshift-install ]]; then
      echo OK
    else
      echo KO
    fi
  register: opinstall_check

- name: Check if oc is installed
  ansible.builtin.shell: |
    if [[ -f /bin/oc ]]; then
      echo OK
    else
      echo KO
    fi
  register: oc_check

- name: Download installation program
  retries: 3
  delay: 5
  ansible.builtin.get_url:
    url: https://github.com/okd-project/okd/releases/download/{{ cluster_version }}/openshift-install-linux-{{ cluster_version }}.tar.gz
    dest: /root/openshift-install-linux.tar.gz
    mode: '0660'
  when: 'opinstall_check.stdout == "KO"'

- name: Extract openshift-install-linux.tar.gz into /root/openshift-install
  ansible.builtin.unarchive:
    remote_src: true
    src: /root/openshift-install-linux.tar.gz
    dest: /root
  when: 'opinstall_check.stdout == "KO"'

- name: Download oc
  retries: 3
  ansible.builtin.get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
    dest: /root/oc.tar.gz
    mode: '0660'
  when: 'oc_check.stdout == "KO"'

- name: Extract oc.tar.gz into /usr/bin
  ansible.builtin.unarchive:
    remote_src: true
    src: /root/oc.tar.gz
    dest: /usr/bin
  when: 'oc_check.stdout == "KO"'