
- name: Create installation directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: 
    -  /root/http-ignition
    -  /root/http-ignition/lib

- name: Copy http-ignition fastapi
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /root/http-ignition
    owner: root
    group: root
    mode: '0644'
  loop:
    - ../http-ignition/main.py
    - ../http-ignition/requirements.txt
    - ./conf/proxmox.yaml

- name: Copy http-ignition fastapi
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /root/http-ignition/lib
    owner: root
    group: root
    mode: '0644'
  loop:
    - ../http-ignition/lib/network.py
    - ../http-ignition/lib/proxmox.py

- name: Set up pip env
  ignore_errors: true
  ansible.builtin.shell: |
    cd /root/http-ignition
    curl -O https://bootstrap.pypa.io/get-pip.py
    /bin/python get-pip.py
    /bin/python -m venv .venv
    
- name: Install specified python requirements
  ansible.builtin.pip:
    virtualenv: /root/http-ignition/.venv
    requirements: /root/http-ignition/requirements.txt

- name: Copy ignition-http.service
  ansible.builtin.copy:
    src: conf/http-ignition/http-ignition.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'
    
- name: Start http-ignition.service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: http-ignition
    daemon_reload: true