- name: "Async stop infrastructure VM"
  ignore_errors: true
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port }}"
    validate_certs: false
    node: "{{ item.node }}"
    name: "{{ item.name }}"
    state: stopped
    force: true
    timeout: 10
  loop: "{{ okd_vm }}"
  loop_control:
    label: "{{ item.name }}"
  async: 90
  poll: 0
  register: vm_stop

- name: "Check VMs stop"
  ignore_errors: true
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 90
  delay: 1
  no_log: true
  loop: "{{ vm_stop.results }}"


- name: "Remove infrastructure"
  ignore_errors: true
  async: 120
  poll: 5
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port }}"
    validate_certs: false
    node: "{{ item.node }}"
    name: "{{ item.name }}"
    state: absent
    force: true
    timeout: 90
  loop: "{{ okd_vm }}"
  loop_control:
    label: "{{ item.name }}"
  async: 90
  poll: 0
