cluster_name: "okd"
domain: "okd.yuki.es"
gateway: "192.168.69.1"
loadbalancer: "192.168.69.230" # virtual ip keepalived
searchdomain: "yuki.es"
haproxy_acl_network: "192.168.69.0/24"
iso_storage: "nas"
disk_storage: "local-zfs"
sshkeys: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIItNs6VIKT7ggUjhfnVedzON41XHI/pUn6A/gS5YHAuM yuki@yukiV2
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+FFDoXjiC4vdqb6GQcQQckEdWJljsE8V/tHIF8DR4i yuki@yukiV2
okd_template_nodes:
  - node: socrates
    id: 105
  - node: platon
    id: 106
dns: 
  - "192.168.69.1"
  - "1.1.1.1"
loadbalancers:
  - name: "anaxagoras-01"
    id: 202
    user: "yuki"
    password: "password"
    ip: "192.168.69.238"
    cores: 4
    memory: 16384
    node: "socrates"
    template: 
      name: "rocky-9-template"
      id: 101
  - name: "anaxagoras-02"
    id: 201
    user: "yuki"
    password: "password"
    ip: "192.168.69.239"
    cores: 4
    memory: 16384
    node: "platon"
    template: 
      name: "rocky-9-template"
      id: 100
bootstrap:
  - name: "tales-01"
    id: 300
    ip: 192.168.69.240
    cores: 4
    memory: 16384
    disk: 50
    node: "socrates"
controlplane:
  - name: "parmenides-01"
    id: 301
    ip: 192.168.69.231
    cores: 4
    memory: 16384
    disk: 50
    node: "socrates"
  - name: "parmenides-02"
    id: 302
    ip: 192.168.69.232
    cores: 4
    memory: 16384
    disk: 50
    node: "platon"
  - name: "parmenides-03"
    id: 303
    ip: 192.168.69.233
    cores: 4
    memory: 16384
    disk: 50
    node: "socrates"
compute:
  - name: "anaximandro-01"
    id: 304
    ip: 192.168.69.234
    cores: 4
    memory: 16384
    node: "platon"
  - name: "anaximandro-02"
    id: 305
    ip: 192.168.69.235
    cores: 4
    memory: 16384
    node: "socrates"
  - name: "anaximandro-03"
    id: 306
    ip: 192.168.69.236
    cores: 4
    memory: 16384
    node: "platon"