# Select cluster version from: https://github.com/okd-project/okd/releases
cluster_version: "4.15.0-0.okd-2024-03-10-010116" 
cluster_name: "okd"
cluster_latency_profile: "MediumUpdateAverageReaction" # Default | MediumUpdateAverageReaction | LowUpdateSlowReaction
searchdomain: "yuki.es"
loadbalancer_ip: "192.168.69.230" # virtual ip keepalived
gateway: "192.168.69.1"
haproxy_acl_network: "192.168.69.0/24"
dns: 
  - "192.168.69.1"
  - "1.1.1.1"
sshkeys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIItNs6VIKT7ggUjhfnVedzON41XHI/pUn6A/gS5YHAuM yuki@yukiV2"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+FFDoXjiC4vdqb6GQcQQckEdWJljsE8V/tHIF8DR4i yuki@yukiV2"
loadbalancer: # you need prepared rhel template
  - name: "anaxagoras-01"
    id: 202
    user: "yuki"
    password: "password"
    ip: "192.168.69.244"
    cores: 2
    memory: 4096
    node: "socrates"
    template: 
      name: "rocky-9-template"
      id: 101
  - name: "anaxagoras-02"
    id: 201
    user: "yuki"
    password: "password"
    ip: "192.168.69.245"
    cores: 2
    memory: 4096
    node: "platon"
    template: 
      name: "rocky-9-template"
      id: 100
bootstrap: # after installation it will be deleted
  - name: "tales-01"
    id: 300
    ip: 192.168.69.246
    cores: 4
    memory: 16384
    disks: 
      - 50
    node: "socrates"
controlplane:
  - name: "parmenides-01"
    id: 301
    ip: 192.168.69.231
    cores: 4
    memory: 16384
    disks: 
      - 100
    node: "socrates"
  - name: "parmenides-02"
    id: 302
    ip: 192.168.69.232
    cores: 4
    memory: 16384
    disks: 
      - 100
    node: "platon"
  - name: "parmenides-03"
    id: 303
    ip: 192.168.69.233
    cores: 4
    memory: 16384
    disks: 
      - 100
    node: "socrates"
compute:
  - name: "anaximandro-01"
    id: 304
    ip: 192.168.69.234
    cores: 6
    memory: 24576
    disks: 
      - 100
    node: "platon"
  - name: "anaximandro-02"
    id: 305
    ip: 192.168.69.235
    cores: 6
    memory: 24576
    disks: 
      - 100
    node: "socrates"
  - name: "anaximandro-03"
    id: 306
    ip: 192.168.69.236
    cores: 6
    memory: 24576
    disks: 
      - 100
    node: "platon"
infra:
  - name: "heraclito-01"
    id: 307
    ip: 192.168.69.237
    cores: 4
    memory: 16384
    disks: 
      - 100
    node: "platon"
  - name: "heraclito-02"
    id: 308
    ip: 192.168.69.238
    cores: 4
    memory: 16384
    disks: 
      - 100
    node: "socrates"
storage:
  - name: "anaximenes-01"
    id: 309
    ip: 192.168.69.239
    cores: 4
    memory: 16384
    disks: 
      - 100
      - 500
    node: "platon"
  - name: "anaximenes-02"
    id: 310
    ip: 192.168.69.240
    cores: 4
    memory: 16384
    disks: 
      - 100
      - 500
    node: "platon"
  - name: "anaximenes-03"
    id: 311
    ip: 192.168.69.241
    cores: 4
    memory: 16384
    disks: 
      - 100
      - 500
    node: "socrates"
monitoring:
  - name: "pitagoras-01"
    id: 311
    ip: 192.168.69.242
    cores: 4
    memory: 16384
    disks: 
      - 100
      - 500
    node: "platon"
  - name: "pitagoras-02"
    id: 312
    ip: 192.168.69.243
    cores: 4
    memory: 16384
    disks: 
      - 100
      - 500
    node: "socrates"